run:
  timeout: 1m
  allow-parallel-runners: true

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  gocyclo:
    min-complexity: 11
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  lll:
    line-length: 120
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gochecknoglobals
    - gocognit
    - godox
    - nestif
    - prealloc
    - revive
    - wsl
    - cyclop
    - durationcheck
    - errorlint
    - forbidigo
    - gci
    - gofumpt
    - makezero
    - predeclared
    - tparallel
  disable:
    - paralleltest
    - bodyclose
    - godot
    - noctx
    - sqlclosecheck
    - testpackage
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

    - path: _test\.go$
      linters:
        - revive
      text: "empty-block"
    - path: _test\.go$
      linters:
        - depguard
      text: "not allowed from list 'Main'"